apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: golang-5424 
  janus-idp.io/tekton: golang-5424
  backstage.io/kubernetes-id: golang-5424
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: golang-5424
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  